# Generated by Django 4.2.5 on 2023-09-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_status_user_teacher"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="teacher",
            field=models.BooleanField(
                default=False, verbose_name='роль "Преподаватель"'
            ),
        ),
    ]
