# Generated by Django 4.2.5 on 2023-09-27 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0004_alter_lessonviewinfo_lesson"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="video_durution",
            new_name="video_duration",
        ),
    ]
