# Generated by Django 4.2.5 on 2023-09-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0005_rename_video_durution_lesson_video_duration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lessonviewinfo",
            old_name="status",
            new_name="view_info",
        ),
    ]
