# Generated by Django 4.2.5 on 2023-09-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0006_rename_status_lessonviewinfo_view_info"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lessonviewinfo",
            old_name="view_info",
            new_name="status",
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_duration",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="lessonviewinfo",
            name="view_time",
            field=models.IntegerField(default=0),
        ),
    ]
