# Generated by Django 4.2.5 on 2023-09-27 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0007_rename_view_info_lessonviewinfo_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonviewinfo",
            name="last_view_datatime",
            field=models.DateField(
                default=datetime.datetime(2023, 9, 27, 14, 17, 40, 549723)
            ),
        ),
    ]
