# Generated by Django 4.2.5 on 2023-09-27 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0008_lessonviewinfo_last_view_datatime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonviewinfo",
            name="last_view_datatime",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 27, 14, 20, 35, 543509)
            ),
        ),
    ]
