# Generated by Django 4.2.5 on 2023-09-22 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0003_alter_lessonview_user_alter_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"verbose_name": "Лекция", "verbose_name_plural": "Лекциии"},
        ),
        migrations.AlterModelOptions(
            name="lessonview",
            options={
                "verbose_name": "Просмотр лекций",
                "verbose_name_plural": "Просмотр лекций",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Курс", "verbose_name_plural": "Курсы"},
        ),
        migrations.AlterField(
            model_name="lesson",
            name="duration",
            field=models.PositiveIntegerField(verbose_name="Длительность видео (сек.)"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="link",
            field=models.URLField(verbose_name="Ссылка на видеоресурс"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="products",
            field=models.ManyToManyField(
                related_name="lessons",
                to="courses.product",
                verbose_name="Название курса",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="title",
            field=models.CharField(max_length=256, verbose_name="Название урока"),
        ),
        migrations.AlterField(
            model_name="lessonview",
            name="view_status",
            field=models.TextField(
                choices=[("N", "Не просмотрено"), ("Y", "Просмотрено")],
                default="N",
                verbose_name="Статус просмотра",
            ),
        ),
        migrations.AlterField(
            model_name="lessonview",
            name="viewed_time",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Просмотрено (сек.)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=256, verbose_name="Название курса"),
        ),
        migrations.AlterField(
            model_name="product",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор курса",
            ),
        ),
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="courses.product",
                        verbose_name="Лекция",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Студент",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="student",
            field=models.ManyToManyField(
                blank=True, through="courses.Students", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
