# Generated by Django 4.2.5 on 2023-09-22 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0004_alter_lesson_options_alter_lessonview_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="students",
            options={"verbose_name": "Студент", "verbose_name_plural": "Студенты"},
        ),
        migrations.RenameField(
            model_name="product",
            old_name="owner",
            new_name="creator",
        ),
        migrations.AlterField(
            model_name="lesson",
            name="products",
            field=models.ManyToManyField(
                related_name="course",
                to="courses.product",
                verbose_name="Название курса",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="student",
            field=models.ManyToManyField(
                blank=True,
                related_name="student",
                through="courses.Students",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Студент",
            ),
        ),
    ]
