# Generated by Django 4.2.5 on 2023-09-23 08:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0006_students_access_alter_lesson_products_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="student",
            field=models.ManyToManyField(
                blank=True,
                through="courses.Students",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Студент",
            ),
        ),
    ]
