# Generated by Django 4.2.5 on 2023-09-23 09:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0007_alter_product_student"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LessonView",
            new_name="Progress",
        ),
    ]
