# Generated by Django 4.2.5 on 2023-09-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_rename_lessonview_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="progress",
            name="time_updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Последний просмотр"
            ),
        ),
    ]
